# Workflow for web app CD on AWS

# Replace <PACKAGE_NAME> <CODESBUCKET> <DEPLOYBUCKET> with actual repo/package name and bucket

name: CD pipeline
env:
    DEPLOY_PACKAGE_NAME: "<PACKAGE_NAME>-${{ github.sha }}.zip"

on:
  push:
      tags: 
          - 'v*'

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v1

      - name: Create ZIP deployment package
        run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id    : ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          aws-region           : ${{ secrets.AWS_REGION }}

      - name: Copy deployment package to S3
        run : aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://<CODESBUCKET>/

      - name: Finish
        run : echo "CI pipeline successfully finished"

  CD:
    runs-on: ubuntu-latest

    strategy:
        matrix:
          node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
            node-version: ${{ matrix.node-version }}
      - name: Npm install
        run: |
            npm install
      - name: Production Build
        run: |
            npm run build
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
            args: --acl public-read --delete
        env:
            AWS_S3_BUCKET: <DEPLOYBUCKET>
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
            AWS_REGION: ${{ secrets.AWS_REGION }}
            SOURCE_DIR: 'build'

